import { NextPage } from "next" 
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
          <title> Create Next App </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="./favicon.icon" />
      </Head>
      <main>
        Welcome to <a href="https://nextjs.org"> NextJS </a>
      </main>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum laborum ratione sequi eaque, provident nisi nemo quasi dicta ipsa magni quos accusantium veritatis cupiditate doloribus eveniet iusto quis blanditiis repellendus!
      </p>
    </>
  )
}
export default Home